### PR TITLE
Extracted data to json, built responsive demo page using new data file

### PR DESCRIPTION
**Pull request by mdjx**
Test page can be viewed at /generated

### CODE REVIEW

**Comment by PsychoData** [comment]
Pulled this over to my local live test site at https://github.com/PsychoData/msportals.xyz/tree/datafiles
Test Site is live and deployed at https://msportals.contoso.one/generated

I also [reworked QuickFilter in my branch](https://github.com/PsychoData/msportals.xyz/pull/4/commits/8b617f648d440b1a27bc2979ee6e50bff0f75c4a) so quickfilter would work on the generated page, but it breaks for the non-generated pages since their page structure is very different. 

To move forward with this, we would just want to generate the appropriate JSONs and fixed MarkDown docs for the End User, US Govt, and 3rdParty Sites to replace the existing ones and one bulk-swap over from manually generated MarkDown to JSON-generated. 

I definitely feel like if it doesn't fix the "Mobile View" issue https://github.com/adamfowlerit/msportals.xyz/issues/35  - it at least drastically improves it. 

I think we could stand to swap out the Shortlink icons, and GCC/US Govt icons for something a bit friendlier. Maybe something that doesn't need an explanation that 🔁 is an Aka.ms link? - this picture suggestion seems like a decent look for the aka.ms https://github.com/adamfowlerit/msportals.xyz/issues/35#issuecomment-724434801
image

**Comment by PsychoData** [comment]
I do have a bonus though for you - I made this yesterday evening to pull down the content off the live, table-based webpage. 
[PageQueries.xlsx](https://github.com/adamfowlerit/msportals.xyz/files/5663943/PageQueries.xlsx)

It doesn't capture the Aka.ms or GCC links inside the Unicode Glyphs, but it still will let you dump the URLs, link titles, and Header they are under from the existing page into CSV for easier processing

**Review by PsychoData — APPROVED** [review]
Fine to Commit to the public repo without any functionality changes to the live site

**Comment by mdjx** [comment]
Few thoughts:

- Is there value in showing the actual URL for each portal? Most people are going to either click the link, or copy the URL, I can't think of too many situations where you need to immediately see the full address.  Replacing it with something that just says 'Link', would make the page look cleaner, and probably help with the mobile experience.

The filter would still work as it reads the underlying href, so if you knew part of the URL and wanted to search by that it would work, however, it may cause a bit of  initial confusion as the string you're filtering by may not be visible on the page. 

I don't have strong opinions on this either way, just throwing it out there. 

- Regarding the icons, I agree that if an explanation is needed then it's probably not great UX. Even text links may work. Something like [this](https://i.imgur.com/IhbM9UR.png), if we combine it with the above idea. One advantage of text links is they're filterable, so if someone was ever after all the US portal links on a page, they could just filter by 'us gov'.

- On the mobile version, one idea was to make the portal name the link, and get rid of the separate URL, This would approximately double the amount of portals that would fit on the screen at any one time.

- The top buttons don't fit with the rest of the design imo, something flatter and less shiny may work better. 

- Make the filter input autofocus on page load. For those not using the filter it shouldn't make any difference, for those using it, it would mean being able to start typing straight away without having to click into it.

**Comment by benstegink** [comment]
Personally, I really like having the actual URL visible on the page. It helps me to learn the URL Once I get to know the URL, I tend to just type it right into the browser. 

If it's just a bunch of "link" text that I can click on, it makes it harder to learn the actual URL, esp. if said URL is a redirect to a more complex URL.

**Comment by mdjx** [comment]
Good point 👍

**Comment by mdjx** [comment]
Quick update

- All portal pages have been converted to use JSON data files
- I've created a template for 'portal' pages which includes all the generating code, this can then be referenced from each portal file (instead of copy pasting the whole block). 

This means the only content left inside the markdown pages is the title, and the first little blurb. If @adamfowlerit likes the idea these can also be moved into the JSON files, so the entire page can be generated from JSON. 

- Lastly, I've pushed my changes, however, as @PsychoData has updated the filter code on his branch I haven't bothered to do it here. This means if this PR is deployed it will break the filter functionality until @PsychoData's filter updates are also deployed.

**Comment by PsychoData** [comment]
> Regarding the icons, I agree that if an explanation is needed then it's probably not great UX. Even text links may work. 

Honestly, I think defaulting to Global Cloud and maybe implementing something down the line to flip between Sovereign cloud varieties, but that one person who requested US Govt page has one for now to use in the meantime so he ought to be fine for now
In the meantime, I'd say lets flip over the site to full-JSON sourced portals, and then I can send over the QuickFilter fix for it

> Make the filter input autofocus on page load. For those not using the filter it shouldn't make any difference, for those using it, it would mean being able to start typing straight away without having to click into it.

Definitely sounds good I was DEFINITELY wanting this last night while I did my testing - doesn't need to happen as part of this PR though

> The top buttons don't fit with the rest of the design imo, something flatter and less shiny may work better.

yeah, it looks weird on mobile too, with the big buttons, even on iPad sized screens 
image

**Comment by PsychoData** [comment]
Merged, and added the QuickFilter changes in this Commit https://github.com/adamfowlerit/msportals.xyz/commit/adb4e063981fce26b64d2ce45d57c88bba6640d0

**Pull request merged**
